"""
Live Trade Execution Engine for TradeForge AI

Generates trading signals from trained models and executes via broker APIs.
Handles: signal generation, order routing, position management, P&L tracking,
 and integration with the risk management layer.

The engine is fully async and designed to run inside an event loop that
receives signals from an LLM-based strategy model.

Typical usage::

    broker = PaperBroker(initial_balance=1_000_000)
    risk = RiskManager(config={"daily_loss_limit": 20000})
    engine = ExecutionEngine(broker, risk, mode=ExecutionMode.PAPER)

    signal = TradeSignal(
        symbol="RELIANCE-EQ", direction="buy", quantity=10,
        price=2450.0, confidence=0.85, strategy_id=1,
        model_version="v1.2.0",
    )
    await engine.on_signal(signal)
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from datetime import datetime, time as dt_time
from enum import Enum
from typing import Any, Callable, Coroutine, Dict, List, Optional, Set

from pydantic import BaseModel, Field, field_validator
from loguru import logger

from core.broker.base import (
    BaseBroker,
    OrderParams,
    OrderResult,
    OrderSide,
    OrderType,
    ProductType,
    Exchange,
    PositionData,
    FundsData,
)
from core.risk_manager import RiskManager, RiskCheckResult


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ExecutionMode(str, Enum):
    """Operating mode of the execution engine."""
    PAPER = "paper"
    LIVE = "live"


class SignalDirection(str, Enum):
    """Direction of a trade signal."""
    BUY = "buy"
    SELL = "sell"


# ---------------------------------------------------------------------------
# Trade signal model
# ---------------------------------------------------------------------------

class TradeSignal(BaseModel):
    """Signal generated by a strategy model (e.g. LLM).

    Attributes:
        symbol: Trading symbol (broker-native format).
        direction: ``buy`` or ``sell``.
        quantity: Number of shares / lots to trade.
        price: Expected / limit price (0 for market orders).
        confidence: Model confidence score (0.0 – 1.0).
        strategy_id: Identifier of the generating strategy.
        model_version: Version string of the model.
        timestamp: UTC time the signal was created.
        order_type: Desired order type (defaults to ``market``).
        product_type: ``mis``, ``cnc``, or ``nrml``.
        exchange: Target exchange.
        metadata: Extra key-value data (e.g. ATR, rationale).
    """

    symbol: str = Field(..., min_length=1)
    direction: SignalDirection
    quantity: int = Field(..., gt=0)
    price: float = Field(default=0.0, ge=0.0)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    strategy_id: str = Field(default="")
    model_version: str = Field(default="unknown")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    order_type: OrderType = Field(default=OrderType.MARKET)
    product_type: ProductType = Field(default=ProductType.MIS)
    exchange: Exchange = Field(default=Exchange.NSE)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("symbol")
    @classmethod
    def _strip_upper(cls, v: str) -> str:
        return v.strip().upper()

    def to_order_params(self) -> OrderParams:
        """Convert signal to broker-agnostic :class:`OrderParams`."""
        # Broker tags are often limited to 8-20 characters; keep the prefix
        # and truncate the strategy id so validation never fails.
        raw_tag = f"TF-{self.strategy_id or '0'}"
        return OrderParams(
            symbol=self.symbol,
            quantity=self.quantity,
            side=OrderSide(self.direction.value),
            order_type=self.order_type,
            product_type=self.product_type,
            exchange=self.exchange,
            price=self.price,
            tag=raw_tag[:20],
        )


# ---------------------------------------------------------------------------
# Position snapshot
# ---------------------------------------------------------------------------

@dataclass
class PositionSnapshot:
    """Lightweight in-memory position tracked by the execution engine."""
    symbol: str
    quantity: int              # Positive = long, Negative = short
    avg_price: float
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    entry_time: Optional[datetime] = None
    strategy_id: str = ""
    model_version: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Execution engine
# ---------------------------------------------------------------------------

class ExecutionEngine:
    """Live execution engine that:

    1. Receives signals from trained strategy models.
    2. Validates every signal through :class:`RiskManager`.
    3. Routes approved orders to the configured broker.
    4. Tracks positions and realised / unrealised P&L.
    5. Applies emergency controls (kill switch, square-off).

    The engine is **stateful**—it maintains ``active_positions`` in memory.
    For durability across restarts, callers should persist the portfolio
    summary periodically.
    """

    def __init__(
        self,
        broker: BaseBroker,
        risk_manager: RiskManager,
        mode: ExecutionMode = ExecutionMode.PAPER,
        callbacks: Optional[Dict[str, Callable[..., Coroutine]]] = None,
    ):
        self.broker = broker
        self.risk = risk_manager
        self.mode = mode
        self.callbacks = callbacks or {}

        # In-memory state
        self.active_positions: Dict[str, PositionSnapshot] = {}
        self.pending_orders: Dict[str, OrderResult] = {}
        self.signal_history: List[Dict[str, Any]] = []
        self.trade_history: List[Dict[str, Any]] = []

        # Daily stats
        self.daily_stats = {
            "trades_today": 0,
            "buys_today": 0,
            "sells_today": 0,
            "pnl_today": 0.0,
            "loss_today": 0.0,
            "volume_traded": 0,
        }

        # Circuit-breaker state
        self._halted: bool = False
        self._halt_reason: str = ""

        logger.info(
            "ExecutionEngine initialised | mode={} broker={}",
            mode.value, broker.name,
        )

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def is_halted(self) -> bool:
        """Return whether trading is currently halted."""
        return self._halted or self.risk.kill_switch_active

    @property
    def position_count(self) -> int:
        """Number of currently tracked positions."""
        return len(self.active_positions)

    # ------------------------------------------------------------------
    # Signal processing
    # ------------------------------------------------------------------

    async def on_signal(self, signal: TradeSignal) -> Dict[str, Any]:
        """Process an incoming trade signal from the model.

        Flow:
            1. Pre-flight checks (mode, halted state)
            2. Risk validation
            3. Route to buy / sell handler
            4. Update state & notify callbacks

        Args:
            signal: The :class:`TradeSignal` to process.

        Returns:
            Dict with ``success``, ``order_id``, ``message``, and
            ``risk_result`` keys.
        """
        ts_start = datetime.utcnow()
        log_ctx = {
            "symbol": signal.symbol,
            "direction": signal.direction.value,
            "qty": signal.quantity,
            "confidence": signal.confidence,
            "strategy": signal.strategy_id,
        }
        logger.info("SIGNAL received | {}", log_ctx)

        # 1. Pre-flight
        if self.is_halted:
            msg = f"Trading HALTED: {self._halt_reason or 'Kill switch active'}"
            logger.warning(msg)
            return {"success": False, "message": msg, "risk_result": None}

        if self.mode == ExecutionMode.LIVE and signal.confidence < 0.6:
            logger.warning("Signal confidence too low for LIVE mode: {}", signal.confidence)
            # In live mode we can optionally reject low-confidence signals
            # return {"success": False, "message": "Low confidence", ...}

        # 2. Risk check
        signal_dict = {
            "symbol": signal.symbol,
            "quantity": signal.quantity,
            "price": signal.price or await self._get_safe_ltp(signal),
            "volatility_pct": signal.metadata.get("volatility_pct", 0.0),
        }
        current_positions = [self._pos_to_dict(p) for p in self.active_positions.values()]
        portfolio_value = await self._get_portfolio_value()

        risk_result = self.risk.check_trade_allowed(
            signal_dict, current_positions, portfolio_value
        )

        if not risk_result.allowed:
            logger.warning(
                "RISK REJECTED | symbol={} reason={}",
                signal.symbol, risk_result.reason,
            )
            self.signal_history.append({
                "signal": signal.model_dump(),
                "risk_result": risk_result.model_dump(),
                "executed": False,
                "timestamp": datetime.utcnow().isoformat(),
            })
            return {
                "success": False,
                "message": risk_result.reason,
                "risk_result": risk_result.model_dump(),
            }

        # Adjust quantity if risk manager suggested a smaller size
        if risk_result.suggested_qty and risk_result.suggested_qty < signal.quantity:
            signal = signal.model_copy(update={"quantity": risk_result.suggested_qty})
            logger.info("Quantity adjusted by risk: {} -> {}", signal_dict["quantity"], signal.quantity)

        # 3. Execute
        try:
            if signal.direction == SignalDirection.BUY:
                result = await self.execute_buy(signal)
            else:
                result = await self.execute_sell(signal)
        except Exception as exc:
            logger.exception("Execution failed for {}: {}", signal.symbol, exc)
            return {
                "success": False,
                "message": f"Execution error: {exc}",
                "risk_result": risk_result.model_dump(),
            }

        # 4. Post-execution bookkeeping
        latency_ms = (datetime.utcnow() - ts_start).total_seconds() * 1000
        self.signal_history.append({
            "signal": signal.model_dump(),
            "risk_result": risk_result.model_dump(),
            "executed": result.is_complete if hasattr(result, "is_complete") else False,
            "order_result": result.model_dump() if isinstance(result, BaseModel) else result,
            "latency_ms": round(latency_ms, 2),
            "timestamp": datetime.utcnow().isoformat(),
        })

        # Callback
        cb = self.callbacks.get("on_trade")
        if cb:
            try:
                await cb(signal, result)
            except Exception:
                logger.exception("Trade callback failed")

        return {
            "success": getattr(result, "is_complete", False),
            "order_id": getattr(result, "order_id", ""),
            "message": getattr(result, "message", ""),
            "risk_result": risk_result.model_dump(),
            "latency_ms": round(latency_ms, 2),
        }

    # ------------------------------------------------------------------
    # Order execution
    # ------------------------------------------------------------------

    async def execute_buy(self, signal: TradeSignal) -> OrderResult:
        """Execute a buy order through the broker.

        If a short position exists for the same symbol, it is squared off
        first (unless configured otherwise).
        """
        symbol = signal.symbol

        # Check if we have a short position to cover
        if symbol in self.active_positions and self.active_positions[symbol].quantity < 0:
            logger.info("Covering short position before buy: {}", symbol)
            await self.close_position(symbol, reason="cover_short")

        # Place order
        order_params = signal.to_order_params()
        result = await self.broker.place_order(order_params)

        if result.is_complete:
            await self._update_position_after_buy(signal, result)
            self.daily_stats["trades_today"] += 1
            self.daily_stats["buys_today"] += 1
            self.daily_stats["volume_traded"] += signal.quantity
            logger.info(
                "BUY executed | {} {} @ {:.2f} order_id={}",
                symbol, signal.quantity, result.avg_price, result.order_id,
            )
        else:
            logger.warning(
                "BUY failed | {} status={} msg={}",
                symbol, result.status.value, result.message,
            )

        return result

    async def execute_sell(self, signal: TradeSignal) -> OrderResult:
        """Execute a sell order through the broker.

        If a long position exists, it is closed.  Otherwise a new short
        position is opened (if allowed).
        """
        symbol = signal.symbol

        # Check if we have a long position to close
        if symbol in self.active_positions and self.active_positions[symbol].quantity > 0:
            logger.info("Closing long position: {}", symbol)
            return await self.close_position(symbol, reason="signal_sell")

        # New short (if not holding)
        order_params = signal.to_order_params()
        result = await self.broker.place_order(order_params)

        if result.is_complete:
            await self._update_position_after_sell(signal, result)
            self.daily_stats["trades_today"] += 1
            self.daily_stats["sells_today"] += 1
            self.daily_stats["volume_traded"] += signal.quantity
            logger.info(
                "SELL/SHORT executed | {} {} @ {:.2f} order_id={}",
                symbol, signal.quantity, result.avg_price, result.order_id,
            )
        else:
            logger.warning(
                "SELL failed | {} status={} msg={}",
                symbol, result.status.value, result.message,
            )

        return result

    # ------------------------------------------------------------------
    # Position management
    # ------------------------------------------------------------------

    async def close_position(
        self,
        symbol: str,
        reason: str = "signal",
    ) -> OrderResult:
        """Close an open position by sending an opposite-side market order.

        Args:
            symbol: Trading symbol to close.
            reason: Human-readable reason for closure.

        Returns:
            :class:`OrderResult` from the closing order.
        """
        symbol = symbol.upper().strip()
        if symbol not in self.active_positions:
            logger.warning("No position to close: {}", symbol)
            return OrderResult(
                order_id="", status=OrderStatus.REJECTED, message="No open position"
            )

        pos = self.active_positions[symbol]
        close_side = OrderSide.SELL if pos.quantity > 0 else OrderSide.BUY
        close_qty = abs(pos.quantity)

        close_params = OrderParams(
            symbol=symbol,
            quantity=close_qty,
            side=close_side,
            order_type=OrderType.MARKET,
            product_type=ProductType.MIS,
            exchange=Exchange.NSE,
            tag=f"close-{reason}",
        )

        result = await self.broker.place_order(close_params)

        if result.is_complete:
            realised = self._calculate_realized_pnl(pos, result.avg_price)
            self.risk.update_after_trade(realised)
            self.daily_stats["pnl_today"] += realised
            if realised < 0:
                self.daily_stats["loss_today"] += abs(realised)

            self.trade_history.append({
                "symbol": symbol,
                "direction": "long" if pos.quantity > 0 else "short",
                "entry_price": pos.avg_price,
                "exit_price": result.avg_price,
                "quantity": close_qty,
                "realized_pnl": round(realised, 2),
                "reason": reason,
                "timestamp": datetime.utcnow().isoformat(),
            })

            del self.active_positions[symbol]
            logger.info(
                "Position closed | {} pnl={:,.2f} reason={}",
                symbol, realised, reason,
            )
        else:
            logger.error(
                "Close position FAILED | {} status={} msg={}",
                symbol, result.status.value, result.message,
            )

        return result

    async def close_all_positions(self, reason: str = "kill_switch") -> List[OrderResult]:
        """Emergency close **all** open positions.

        Args:
            reason: Reason for mass closure.

        Returns:
            List of :class:`OrderResult` objects—one per position.
        """
        logger.critical("CLOSE ALL POSITIONS | reason={} count={}", reason, self.position_count)

        symbols = list(self.active_positions.keys())
        results: List[OrderResult] = []

        for symbol in symbols:
            try:
                result = await self.close_position(symbol, reason=reason)
                results.append(result)
            except Exception as exc:
                logger.exception("Failed to close {}: {}", symbol, exc)

        self._halted = True
        self._halt_reason = reason
        return results

    # ------------------------------------------------------------------
    # Portfolio queries
    # ------------------------------------------------------------------

    def get_portfolio_summary(self) -> Dict[str, Any]:
        """Get current portfolio state snapshot.

        Returns:
            Dict with positions, realised P&L, daily stats, and risk summary.
        """
        unrealized = sum(p.unrealized_pnl for p in self.active_positions.values())
        realized = sum(t.get("realized_pnl", 0) for t in self.trade_history)

        return {
            "mode": self.mode.value,
            "halted": self.is_halted,
            "halt_reason": self._halt_reason,
            "position_count": self.position_count,
            "positions": {
                sym: {
                    "symbol": p.symbol,
                    "quantity": p.quantity,
                    "avg_price": p.avg_price,
                    "current_price": p.current_price,
                    "unrealized_pnl": round(p.unrealized_pnl, 2),
                    "realized_pnl": round(p.realized_pnl, 2),
                }
                for sym, p in self.active_positions.items()
            },
            "total_unrealized_pnl": round(unrealized, 2),
            "total_realized_pnl": round(realized, 2),
            "daily_stats": self.daily_stats.copy(),
            "total_signals_processed": len(self.signal_history),
            "total_trades_executed": len(self.trade_history),
            "risk_summary": self.risk.get_risk_summary(),
        }

    async def sync_positions(self) -> None:
        """Synchronise in-memory positions with the broker.

        Useful after a restart to reconcile state.
        """
        try:
            broker_positions = await self.broker.get_positions()
            self.active_positions = {}
            for bp in broker_positions:
                self.active_positions[bp.symbol] = PositionSnapshot(
                    symbol=bp.symbol,
                    quantity=bp.quantity,
                    avg_price=bp.avg_price,
                    current_price=bp.last_price,
                    unrealized_pnl=bp.pnl,
                )
            logger.info("Positions synced | count={}", len(self.active_positions))
        except Exception as exc:
            logger.exception("Position sync failed: {}", exc)

    # ------------------------------------------------------------------
    # Daily lifecycle
    # ------------------------------------------------------------------

    def reset_daily_stats(self) -> None:
        """Reset daily counters.  Call at market open (09:00)."""
        self.daily_stats = {
            "trades_today": 0,
            "buys_today": 0,
            "sells_today": 0,
            "pnl_today": 0.0,
            "loss_today": 0.0,
            "volume_traded": 0,
        }
        self.risk.reset_daily()
        self._halted = False
        self._halt_reason = ""
        logger.info("Daily stats reset for new session")

    async def pre_market_setup(self) -> None:
        """Run pre-market routines: connect, sync, reset."""
        logger.info("Pre-market setup starting...")
        await self.broker.connect()
        self.reset_daily_stats()
        await self.sync_positions()
        logger.info("Pre-market setup complete")

    async def post_market_cleanup(self) -> None:
        """Run post-market routines: square-off, disconnect."""
        logger.info("Post-market cleanup starting...")
        if self.position_count > 0:
            await self.close_all_positions(reason="market_close")
        await self.broker.disconnect()
        logger.info("Post-market cleanup complete")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _get_safe_ltp(self, signal: TradeSignal) -> float:
        """Fetch LTP with fallback to signal price."""
        try:
            return await self.broker.get_ltp(signal.symbol, signal.exchange)
        except Exception:
            return signal.price or 0.0

    async def _get_portfolio_value(self) -> float:
        """Get total portfolio value (funds + positions)."""
        try:
            funds = await self.broker.get_funds()
            cash = funds.available_cash
        except Exception:
            cash = 1_000_000.0  # Fallback

        position_value = sum(
            abs(p.quantity) * p.current_price
            for p in self.active_positions.values()
        )
        return cash + position_value

    async def _update_position_after_buy(self, signal: TradeSignal, result: OrderResult) -> None:
        """Update internal position tracking after a buy fill."""
        symbol = signal.symbol
        if symbol in self.active_positions:
            pos = self.active_positions[symbol]
            # Averaging
            total_cost = pos.avg_price * pos.quantity + result.avg_price * signal.quantity
            pos.quantity += signal.quantity
            pos.avg_price = total_cost / pos.quantity if pos.quantity > 0 else 0
            pos.current_price = result.avg_price
        else:
            self.active_positions[symbol] = PositionSnapshot(
                symbol=symbol,
                quantity=signal.quantity,
                avg_price=result.avg_price,
                current_price=result.avg_price,
                entry_time=datetime.utcnow(),
                strategy_id=signal.strategy_id,
                model_version=signal.model_version,
            )

    async def _update_position_after_sell(self, signal: TradeSignal, result: OrderResult) -> None:
        """Update internal position tracking after a sell fill."""
        symbol = signal.symbol
        if symbol in self.active_positions:
            pos = self.active_positions[symbol]
            if pos.quantity > 0:
                # Reducing long
                close_qty = min(signal.quantity, pos.quantity)
                realised = (result.avg_price - pos.avg_price) * close_qty
                pos.realized_pnl += realised
                pos.quantity -= close_qty
                if pos.quantity <= 0:
                    del self.active_positions[symbol]
            else:
                # Adding to short
                pos.quantity -= signal.quantity
                pos.avg_price = result.avg_price
        else:
            # New short
            self.active_positions[symbol] = PositionSnapshot(
                symbol=symbol,
                quantity=-signal.quantity,
                avg_price=result.avg_price,
                current_price=result.avg_price,
                entry_time=datetime.utcnow(),
                strategy_id=signal.strategy_id,
                model_version=signal.model_version,
            )

    def _calculate_realized_pnl(self, pos: PositionSnapshot, exit_price: float) -> float:
        """Calculate realised P&L for a position closure."""
        if pos.quantity > 0:
            return (exit_price - pos.avg_price) * pos.quantity
        return (pos.avg_price - exit_price) * abs(pos.quantity)

    def _pos_to_dict(self, pos: PositionSnapshot) -> Dict[str, Any]:
        """Convert PositionSnapshot to dict for risk manager."""
        return {
            "symbol": pos.symbol,
            "quantity": pos.quantity,
            "avg_price": pos.avg_price,
            "last_price": pos.current_price,
        }

    # ------------------------------------------------------------------
    # Health check
    # ------------------------------------------------------------------

    async def health_check(self) -> Dict[str, Any]:
        """Quick health check of the execution pipeline.

        Returns:
            Dict with connectivity, risk state, and position count.
        """
        broker_connected = False
        try:
            broker_connected = self.broker.is_connected
        except Exception:
            pass

        return {
            "status": "healthy" if broker_connected and not self.is_halted else "degraded",
            "broker_connected": broker_connected,
            "halted": self.is_halted,
            "mode": self.mode.value,
            "positions": self.position_count,
            "pending_orders": len(self.pending_orders),
            "daily_stats": self.daily_stats.copy(),
        }
