"""
TradeForge AI — Pure-Function Technical Indicator Library.

Every indicator is implemented as a stateless pure function that accepts
Pandas Series (or DataFrames) and returns a new Series.  This makes them
naturally composable, testable, and safe for use inside strategy code
generated by the LLM.

All functions handle edge cases (insufficient data, NaN propagation) through
the underlying Pandas rolling-window machinery.
"""

from __future__ import annotations

from typing import Tuple

import numpy as np
import pandas as pd
from loguru import logger


# ---------------------------------------------------------------------------
# Moving Averages
# ---------------------------------------------------------------------------


def sma(series: pd.Series, period: int) -> pd.Series:
    """Simple Moving Average (SMA).

    Parameters
    ----------
    series:
        Input price series.
    period:
        Look-back window length (must be >= 1).

    Returns
    -------
    pd.Series
        SMA values aligned to the input index.  Leading ``period-1`` values
        are ``NaN``.
    """
    if period < 1:
        raise ValueError(f"period must be >= 1, got {period}")
    return series.rolling(window=period, min_periods=period).mean()


def ema(series: pd.Series, period: int) -> pd.Series:
    """Exponential Moving Average (EMA).

    Parameters
    ----------
    series:
        Input price series.
    period:
        Span for the exponential weighting.

    Returns
    -------
    pd.Series
        EMA values.  The first ``period`` values gradually converge.
    """
    if period < 1:
        raise ValueError(f"period must be >= 1, got {period}")
    return series.ewm(span=period, adjust=False, min_periods=period).mean()


def wma(series: pd.Series, period: int) -> pd.Series:
    """Weighted Moving Average (WMA) with linearly increasing weights.

    Parameters
    ----------
    series:
        Input price series.
    period:
        Look-back window length.

    Returns
    -------
    pd.Series
        WMA values.  Leading ``period-1`` values are ``NaN``.
    """
    if period < 1:
        raise ValueError(f"period must be >= 1, got {period}")
    weights = np.arange(1, period + 1, dtype=float)

    def _wma_window(vals: np.ndarray) -> float:
        return float(np.dot(vals, weights) / weights.sum())

    return series.rolling(window=period, min_periods=period).apply(
        _wma_window, raw=True
    )


def hma(series: pd.Series, period: int) -> pd.Series:
    """Hull Moving Average (HMA) — reduced lag moving average.

    Parameters
    ----------
    series:
        Input price series.
    period:
        Look-back window length.

    Returns
    -------
    pd.Series
        HMA values.
    """
    if period < 1:
        raise ValueError(f"period must be >= 1, got {period}")
    half_period = period // 2
    sqrt_period = int(np.sqrt(period))
    raw = 2.0 * ema(series, half_period) - ema(series, period)
    return ema(raw, sqrt_period)


# ---------------------------------------------------------------------------
# Momentum Oscillators
# ---------------------------------------------------------------------------


def rsi(series: pd.Series, period: int = 14) -> pd.Series:
    """Relative Strength Index (RSI).

    Classic 0-100 momentum oscillator measuring speed / magnitude of
    price movements.

    Parameters
    ----------
    series:
        Input price series (typically close).
    period:
        Look-back window (default 14).

    Returns
    -------
    pd.Series
        RSI values in the range [0, 100].  Leading ``period`` values are
        ``NaN``.
    """
    if period < 1:
        raise ValueError(f"period must be >= 1, got {period}")
    delta = series.diff()
    gain = delta.where(delta > 0, 0.0)
    loss = (-delta).where(delta < 0, 0.0)

    avg_gain = gain.rolling(window=period, min_periods=period).mean()
    avg_loss = loss.rolling(window=period, min_periods=period).mean()

    rs = avg_gain / avg_loss
    rsi_vals = 100.0 - (100.0 / (1.0 + rs))
    return rsi_vals


def macd(
    series: pd.Series,
    fast: int = 12,
    slow: int = 26,
    signal: int = 9,
) -> Tuple[pd.Series, pd.Series, pd.Series]:
    """Moving Average Convergence Divergence (MACD).

    Parameters
    ----------
    series:
        Input price series.
    fast:
        Fast EMA span (default 12).
    slow:
        Slow EMA span (default 26).
    signal:
        Signal-line EMA span (default 9).

    Returns
    -------
    tuple[pd.Series, pd.Series, pd.Series]
        ``(macd_line, signal_line, histogram)``
    """
    if fast >= slow:
        raise ValueError(f"fast ({fast}) must be < slow ({slow})")
    macd_line = ema(series, fast) - ema(series, slow)
    signal_line = ema(macd_line, signal)
    histogram = macd_line - signal_line
    return macd_line, signal_line, histogram


def stochastic(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    k_period: int = 14,
    d_period: int = 3,
) -> Tuple[pd.Series, pd.Series]:
    """Stochastic Oscillator (%K and %D).

    Parameters
    ----------
    high, low, close:
        OHLC high, low, and close series.
    k_period:
        Look-back for the %K calculation (default 14).
    d_period:
        SMA smoothing for %D (default 3).

    Returns
    -------
    tuple[pd.Series, pd.Series]
        ``(%K, %D)`` series in the range [0, 100].
    """
    lowest_low = low.rolling(window=k_period, min_periods=k_period).min()
    highest_high = high.rolling(window=k_period, min_periods=k_period).max()

    denom = highest_high - lowest_low
    # Avoid division-by-zero — where range is zero, %K is 50 (neutral).
    pct_k = 100.0 * (close - lowest_low) / denom.replace(0.0, np.nan)
    pct_k = pct_k.fillna(50.0)

    pct_d = pct_k.rolling(window=d_period, min_periods=d_period).mean()
    return pct_k, pct_d


def cci(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    period: int = 20,
) -> pd.Series:
    """Commodity Channel Index (CCI).

    Parameters
    ----------
    high, low, close:
        OHLC series.
    period:
        Look-back window (default 20).

    Returns
    -------
    pd.Series
        CCI values.  Values > +100 or < -100 indicate overbought / oversold.
    """
    tp = (high + low + close) / 3.0
    sma_tp = tp.rolling(window=period, min_periods=period).mean()
    mean_dev = tp.rolling(window=period, min_periods=period).apply(
        lambda x: float(np.abs(x - x.mean()).mean()), raw=True
    )
    return (tp - sma_tp) / (0.015 * mean_dev.replace(0.0, np.nan))


def mfi(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    volume: pd.Series,
    period: int = 14,
) -> pd.Series:
    """Money Flow Index (MFI) — volume-weighted RSI.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    volume:
        Volume series.
    period:
        Look-back window (default 14).

    Returns
    -------
    pd.Series
        MFI values in the range [0, 100].
    """
    tp = (high + low + close) / 3.0
    raw_mf = tp * volume

    tp_shifted = tp.shift(1)
    positive_mf = pd.Series(
        np.where(tp > tp_shifted, raw_mf, 0.0),
        index=close.index,
        dtype=float,
    )
    negative_mf = pd.Series(
        np.where(tp < tp_shifted, raw_mf, 0.0),
        index=close.index,
        dtype=float,
    )

    pmf_sum = positive_mf.rolling(window=period, min_periods=period).sum()
    nmf_sum = negative_mf.rolling(window=period, min_periods=period).sum()

    ratio = pmf_sum / nmf_sum.replace(0.0, np.nan)
    mfi_vals = 100.0 - (100.0 / (1.0 + ratio))
    return mfi_vals


def williams_r(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    period: int = 14,
) -> pd.Series:
    """Williams %R — momentum oscillator similar to Stochastic.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    period:
        Look-back window (default 14).

    Returns
    -------
    pd.Series
        Values range from -100 (oversold) to 0 (overbought).
    """
    highest_high = high.rolling(window=period, min_periods=period).max()
    lowest_low = low.rolling(window=period, min_periods=period).min()
    denom = highest_high - lowest_low
    return -100.0 * (highest_high - close) / denom.replace(0.0, np.nan)


# ---------------------------------------------------------------------------
# Trend
# ---------------------------------------------------------------------------


def adx(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    period: int = 14,
) -> pd.Series:
    """Average Directional Index (ADX).

    Measures trend strength regardless of direction.  Values > 25 generally
    indicate a trending market.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    period:
        Look-back window (default 14).

    Returns
    -------
    pd.Series
        ADX values ranging from 0 to 100.
    """
    # True Range
    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

    atr_vals = tr.rolling(window=period, min_periods=period).mean()

    # Directional Movement
    plus_dm = high.diff()
    minus_dm = -low.diff()

    plus_dm = plus_dm.where((plus_dm > minus_dm) & (plus_dm > 0.0), 0.0)
    minus_dm = minus_dm.where((minus_dm > plus_dm) & (minus_dm > 0.0), 0.0)

    plus_di = 100.0 * plus_dm.rolling(window=period, min_periods=period).mean() / atr_vals.replace(0.0, np.nan)
    minus_di = 100.0 * minus_dm.rolling(window=period, min_periods=period).mean() / atr_vals.replace(0.0, np.nan)

    dx = 100.0 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0.0, np.nan)
    adx_vals = dx.rolling(window=period, min_periods=period).mean()
    return adx_vals


# ---------------------------------------------------------------------------
# Volatility
# ---------------------------------------------------------------------------


def bollinger_bands(
    series: pd.Series,
    period: int = 20,
    std_dev: float = 2.0,
) -> Tuple[pd.Series, pd.Series, pd.Series]:
    """Bollinger Bands (BB).

    Parameters
    ----------
    series:
        Input price series.
    period:
        SMA look-back (default 20).
    std_dev:
        Number of standard deviations (default 2.0).

    Returns
    -------
    tuple[pd.Series, pd.Series, pd.Series]
        ``(upper_band, middle_band, lower_band)``
    """
    middle = sma(series, period)
    std = series.rolling(window=period, min_periods=period).std()
    upper = middle + std * std_dev
    lower = middle - std * std_dev
    return upper, middle, lower


def atr(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    period: int = 14,
) -> pd.Series:
    """Average True Range (ATR) — volatility measure.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    period:
        Look-back window (default 14).

    Returns
    -------
    pd.Series
        ATR values (in price units).
    """
    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    return tr.rolling(window=period, min_periods=period).mean()


def keltner_channels(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    period: int = 20,
    atr_multiplier: float = 2.0,
) -> Tuple[pd.Series, pd.Series, pd.Series]:
    """Keltner Channels — volatility-based envelopes.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    period:
        EMA look-back for the middle line (default 20).
    atr_multiplier:
        ATR multiplier for channel width (default 2.0).

    Returns
    -------
    tuple[pd.Series, pd.Series, pd.Series]
        ``(upper_channel, middle_line, lower_channel)``
    """
    middle = ema(close, period)
    atr_vals = atr(high, low, close, period)
    upper = middle + atr_multiplier * atr_vals
    lower = middle - atr_multiplier * atr_vals
    return upper, middle, lower


def supertrend(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    period: int = 10,
    multiplier: float = 3.0,
) -> Tuple[pd.Series, pd.Series]:
    """SuperTrend indicator — simplified upper/lower bands.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    period:
        ATR look-back (default 10).
    multiplier:
        ATR multiplier for band width (default 3.0).

    Returns
    -------
    tuple[pd.Series, pd.Series]
        ``(upper_band, lower_band)``
    """
    hl2 = (high + low) / 2.0
    atr_vals = atr(high, low, close, period)
    upper_band = hl2 + multiplier * atr_vals
    lower_band = hl2 - multiplier * atr_vals
    return upper_band, lower_band


def psar(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    af: float = 0.02,
    max_af: float = 0.2,
) -> pd.Series:
    """Parabolic SAR (PSAR) — simplified implementation.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    af:
        Initial acceleration factor (default 0.02).
    max_af:
        Maximum acceleration factor (default 0.20).

    Returns
    -------
    pd.Series
        PSAR values aligned to the input index.
    """
    n = len(close)
    psar_vals = pd.Series(index=close.index, dtype=float)
    if n == 0:
        return psar_vals

    # Initialise
    bull = True
    psar_val = float(low.iloc[0])
    ep = float(high.iloc[0])  # Extreme point
    af_val = af

    psar_vals.iloc[0] = psar_val

    for i in range(1, n):
        h = float(high.iloc[i])
        l_val = float(low.iloc[i])

        if bull:
            psar_val = psar_val + af_val * (ep - psar_val)
            # Ensure PSAR is below the last two lows
            psar_val = min(psar_val, float(low.iloc[i - 1]), l_val)
            if h > ep:
                ep = h
                af_val = min(af_val + af, max_af)
            # Bearish reversal
            if l_val < psar_val:
                bull = False
                psar_val = ep
                ep = l_val
                af_val = af
        else:
            psar_val = psar_val + af_val * (ep - psar_val)
            psar_val = max(psar_val, float(high.iloc[i - 1]), h)
            if l_val < ep:
                ep = l_val
                af_val = min(af_val + af, max_af)
            # Bullish reversal
            if h > psar_val:
                bull = True
                psar_val = ep
                ep = h
                af_val = af

        psar_vals.iloc[i] = psar_val

    return psar_vals


# ---------------------------------------------------------------------------
# Volume
# ---------------------------------------------------------------------------


def vwap(
    high: pd.Series,
    low: pd.Series,
    close: pd.Series,
    volume: pd.Series,
) -> pd.Series:
    """Volume-Weighted Average Price (VWAP) — cumulative since series start.

    Parameters
    ----------
    high, low, close:
        OHLC series.
    volume:
        Volume series.

    Returns
    -------
    pd.Series
        Cumulative VWAP.  Resets automatically if you call this on a
        daily slice of intraday data.
    """
    typical_price = (high + low + close) / 3.0
    cum_tp_vol = (typical_price * volume).cumsum()
    cum_vol = volume.cumsum()
    return cum_tp_vol / cum_vol.replace(0.0, np.nan)


def obv(close: pd.Series, volume: pd.Series) -> pd.Series:
    """On-Balance Volume (OBV) — cumulative volume flow.

    Parameters
    ----------
    close:
        Close price series.
    volume:
        Volume series.

    Returns
    -------
    pd.Series
        Cumulative OBV values.
    """
    obv_vals = pd.Series(index=close.index, dtype=float)
    if len(close) == 0:
        return obv_vals

    obv_vals.iloc[0] = float(volume.iloc[0])
    close_shifted = close.shift(1)

    for i in range(1, len(close)):
        if close.iloc[i] > close_shifted.iloc[i]:
            obv_vals.iloc[i] = obv_vals.iloc[i - 1] + float(volume.iloc[i])
        elif close.iloc[i] < close_shifted.iloc[i]:
            obv_vals.iloc[i] = obv_vals.iloc[i - 1] - float(volume.iloc[i])
        else:
            obv_vals.iloc[i] = obv_vals.iloc[i - 1]

    return obv_vals


def vwma(
    close: pd.Series,
    volume: pd.Series,
    period: int = 20,
) -> pd.Series:
    """Volume-Weighted Moving Average (VWMA).

    Parameters
    ----------
    close:
        Close price series.
    volume:
        Volume series.
    period:
        Look-back window (default 20).

    Returns
    -------
    pd.Series
        VWMA values.
    """
    tp_vol = close * volume
    return tp_vol.rolling(window=period, min_periods=period).sum() / volume.rolling(window=period, min_periods=period).sum().replace(0.0, np.nan)


# ---------------------------------------------------------------------------
# Composite helpers
# ---------------------------------------------------------------------------


def calculate_all_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Calculate the full suite of indicators on an OHLCV DataFrame.

    Adds the following columns to a *copy* of the input:
    ``sma_20``, ``sma_50``, ``ema_20``, ``ema_50``, ``rsi_14``,
    ``macd``, ``macd_signal``, ``macd_hist``, ``bb_upper``, ``bb_middle``,
    ``bb_lower``, ``atr_14``, ``vwap``, ``stoch_k``, ``stoch_d``, ``adx``,
    ``obv``.

    Parameters
    ----------
    df:
        DataFrame containing at minimum ``open``, ``high``, ``low``,
        ``close``, ``volume`` columns.

    Returns
    -------
    pd.DataFrame
        New DataFrame with all indicator columns appended.
    """
    required = {"open", "high", "low", "close", "volume"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    result = df.copy()
    logger.debug("Calculating all technical indicators …")

    # Moving averages
    result["sma_20"] = sma(result["close"], 20)
    result["sma_50"] = sma(result["close"], 50)
    result["ema_20"] = ema(result["close"], 20)
    result["ema_50"] = ema(result["close"], 50)

    # Momentum
    result["rsi_14"] = rsi(result["close"], 14)
    result["macd"], result["macd_signal"], result["macd_hist"] = macd(
        result["close"]
    )
    result["stoch_k"], result["stoch_d"] = stochastic(
        result["high"], result["low"], result["close"]
    )

    # Volatility
    result["bb_upper"], result["bb_middle"], result["bb_lower"] = bollinger_bands(
        result["close"]
    )
    result["atr_14"] = atr(
        result["high"], result["low"], result["close"], 14
    )

    # Trend
    result["adx"] = adx(result["high"], result["low"], result["close"])

    # Volume
    result["vwap"] = vwap(
        result["high"], result["low"], result["close"], result["volume"]
    )
    result["obv"] = obv(result["close"], result["volume"])

    logger.debug("Indicator calculation complete")
    return result
