import type { SavedStrategy } from './types';

export const MOCK_STRATEGIES: SavedStrategy[] = [
  {
    id: '1',
    name: 'Momentum Crossover',
    description: 'SMA 20 crosses above SMA 50 with volume confirmation',
    instrument: 'NIFTY 50',
    segment: 'Stocks',
    status: 'active',
    lastModified: '2 hours ago',
    timeframe: '1D',
    entryConditions: [
      { id: 'e1', indicator: 'SMA(20)', operator: 'crosses_above', value: 'SMA(50)', valueType: 'indicator' },
      { id: 'e2', indicator: 'Volume', operator: '>', value: 'SMA(Volume,20)*1.5', valueType: 'indicator', logic: 'AND' },
    ],
    exitConditions: [
      { id: 'x1', indicator: 'SMA(20)', operator: 'crosses_below', value: 'SMA(50)', valueType: 'indicator' },
      { id: 'x2', indicator: 'RSI(14)', operator: '>', value: '70', valueType: 'number', logic: 'OR' },
    ],
    stopLoss: { type: 'fixed', value: 1.5 },
    target: { type: 'rr', value: 2.0 },
    positionSizing: { type: 'percent', value: 10 },
  },
  {
    id: '2',
    name: 'RSI Reversal',
    description: 'Mean reversion using RSI oversold/overbought levels',
    instrument: 'RELIANCE',
    segment: 'Stocks',
    status: 'paper',
    lastModified: '1 day ago',
    timeframe: '1H',
    entryConditions: [
      { id: 'e1', indicator: 'RSI(14)', operator: 'crosses_above', value: '30', valueType: 'number' },
      { id: 'e2', indicator: 'Price', operator: '>', value: 'VWAP', valueType: 'indicator', logic: 'AND' },
    ],
    exitConditions: [
      { id: 'x1', indicator: 'RSI(14)', operator: '>', value: '70', valueType: 'number' },
      { id: 'x2', indicator: 'Target', operator: '', value: '2%', valueType: 'number', logic: 'OR' },
    ],
    stopLoss: { type: 'fixed', value: 1.0 },
    target: { type: 'fixed', value: 2.0 },
    positionSizing: { type: 'fixed', value: 100 },
  },
  {
    id: '3',
    name: 'Bollinger Bounce',
    description: 'Price touches lower band and reverses with RSI confirmation',
    instrument: 'BANKNIFTY',
    segment: 'Futures',
    status: 'backtesting',
    lastModified: '3 hours ago',
    timeframe: '15m',
    entryConditions: [
      { id: 'e1', indicator: 'Price', operator: '<', value: 'BB Lower', valueType: 'indicator' },
      { id: 'e2', indicator: 'RSI(14)', operator: '>', value: '40', valueType: 'number', logic: 'AND' },
    ],
    exitConditions: [
      { id: 'x1', indicator: 'Price', operator: '>', value: 'BB Upper', valueType: 'indicator' },
      { id: 'x2', indicator: 'ATR(14)*1.5', operator: '', value: 'Trailing Stop', valueType: 'indicator', logic: 'OR' },
    ],
    stopLoss: { type: 'atr', value: 1.5 },
    target: { type: 'fixed', value: 3.0 },
    positionSizing: { type: 'risk', value: 1 },
  },
  {
    id: '4',
    name: 'VWAP Pullback',
    description: 'Trend following entries on VWAP pullbacks',
    instrument: 'NIFTY 50',
    segment: 'Futures',
    status: 'draft',
    lastModified: '5 days ago',
    timeframe: '5m',
    entryConditions: [
      { id: 'e1', indicator: 'Price', operator: 'crosses_above', value: 'VWAP', valueType: 'indicator' },
      { id: 'e2', indicator: 'ADX(14)', operator: '>', value: '25', valueType: 'number', logic: 'AND' },
    ],
    exitConditions: [
      { id: 'x1', indicator: 'Price', operator: 'crosses_below', value: 'VWAP', valueType: 'indicator' },
    ],
    stopLoss: { type: 'trailing', value: 0.5 },
    target: { type: 'rr', value: 3.0 },
    positionSizing: { type: 'percent', value: 5 },
  },
  {
    id: '5',
    name: 'MACD Momentum',
    description: 'MACD line crosses signal line with histogram confirmation',
    instrument: 'INFY',
    segment: 'Stocks',
    status: 'draft',
    lastModified: '1 week ago',
    timeframe: '1D',
    entryConditions: [
      { id: 'e1', indicator: 'MACD Line', operator: 'crosses_above', value: 'Signal', valueType: 'indicator' },
      { id: 'e2', indicator: 'MACD Hist', operator: '>', value: '0', valueType: 'number', logic: 'AND' },
    ],
    exitConditions: [
      { id: 'x1', indicator: 'MACD Line', operator: 'crosses_below', value: 'Signal', valueType: 'indicator' },
    ],
    stopLoss: { type: 'fixed', value: 2.0 },
    target: { type: 'fixed', value: 4.0 },
    positionSizing: { type: 'percent', value: 15 },
  },
];
